## application.yml

spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB       # 파일 하나의 최대 크기
      max-request-size: 10MB    # 요청 전체 크기 (파일 여러 개 포함 시)